# Generated by Django 4.1.7 on 2023-08-14 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodshop', '0004_remove_product_user_merchant_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchant',
            name='user',
        ),
    ]
