# Generated by Django 4.1.7 on 2023-08-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodshop', '0007_alter_product_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight_unit',
            field=models.CharField(choices=[('kg', 'kg'), ('g', 'g')], default='g', max_length=2),
        ),
    ]
