# Generated by Django 4.1.7 on 2023-08-24 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodshop', '0011_alter_customuser_email_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
