# Generated by Django 4.1.7 on 2023-08-24 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodshop', '0014_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
